---

# common
- hosts: all
  become: yes
  gather_facts: no
  become_user: root

  roles:
    - common

# web
- hosts: web
  sudo: yes

  roles:
    - web

# lb
- hosts: lb
  sudo: yes  

  roles:
    - lb
